In [6]:
import numpy as np
import time


In [5]:
# Speed comparison
big_list  = list(range(1000000))
big_array = np.array(range(1000000))

# List — slow
start = time.time()
result = [x * 2 for x in big_list]
print(f"List:  {time.time() - start:.4f}s")

# NumPy — fast!
start = time.time()
result = big_array * 2  # vectorized!
print(f"NumPy: {time.time() - start:.4f}s")

# NumPy is 10-100x faster! ✅

List:  0.0741s
NumPy: 0.0210s


In [9]:
# Creating Array

arr = np.array([1,2,3,4])
print(arr)

# 2D array
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# Special arrays
# 3x4 array of 0s

print("3x4 array of 0s")
print(np.zeros((3,4)))


3x4 array of 0s
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2x3 array of 1s
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print("2x3 array of 1s")
print(np.ones((2,3)))

2x3 array of 1s
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# 3x3 array of 7s
np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [19]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# random 0-1 values
np.random.rand(3, 3)

array([[0.34020024, 0.38311869, 0.75027274],
       [0.90830688, 0.72898604, 0.59117294],
       [0.3596511 , 0.389088  , 0.72355135]])

In [24]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)    # (2, 3) → 2 rows, 3 cols
print(arr.ndim)     # 2 → dimensions
print(arr.size)     # 6 → total elements
print(arr.dtype)    # int64 → data type

# Change data type
arr = np.array([1.5, 2.7, 3.9])
arr_int = arr.astype(int)   # [1, 2, 3]
arr_str = arr.astype(str)   # ['1.5','2.7']

(2, 3)
2
6
int64


In [25]:
arr = np.array([10, 20, 30, 40, 50])

# Single element
print(arr[0])    # 10
print(arr[-1])   # 50

# Slicing
print(arr[1:4])  # [20, 30, 40]
print(arr[:3])   # [10, 20, 30]
print(arr[::2])  # [10, 30, 50]

# 2D indexing
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[0, 0])   # 1 (row0, col0)
print(matrix[1, 2])   # 6 (row1, col2)
print(matrix[0, :])   # [1,2,3] row 0
print(matrix[:, 1])   # [2,5,8] col 1
print(matrix[0:2, 1:3]) # submatrix

10
50
[20 30 40]
[10 20 30]
[10 30 50]
1
6
[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


In [26]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

# Airthmetic Operations
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 1  4  9 16 25]


In [29]:
#Scalar Operations

premiums = np.array([4500,2300,5600,
                    1800,3200,4700])
print(premiums*1.1)
print(premiums+500)
print(premiums>3000)

[4950. 2530. 6160. 1980. 3520. 5170.]
[5000 2800 6100 2300 3700 5200]
[ True False  True False  True  True]


In [34]:
# Statistical Functions

premiums = np.array([
    4500,2300,5600,
    1800,3200,4700
])

print(np.sum(premiums))
print(np.mean(premiums))
print(np.median(premiums))
print(np.std(premiums))
print(np.var(premiums))
print(np.min(premiums))
print(np.max(premiums))
print(np.argmin(premiums))
print(np.argmax(premiums))

22100
3683.3333333333335
3850.0
1358.2055154586224
1844722.2222222222
1800
5600
3
2


In [35]:
# Cumulative
print(np.cumsum(premiums))  # running total
print(np.cumprod([1,2,3]))  # running product


[ 4500  6800 12400 14200 17400 22100]
[1 2 6]


In [36]:
# Percentile
print(np.percentile(premiums, 25))  # Q1
print(np.percentile(premiums, 75))  # Q3

2525.0
4650.0


In [ ]:
# Array Operations
a = np.array([1,2,3])
b = np.array([4,5,6])

# 